services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: web_bot_api
    ports:
      - '5000:5000'
    
    volumes:
      - .:/app
      - ./chroma_data:/app/chroma_data